#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


METHOD_LABELS = {
    "scratch": "Scratch",
    "reconst": "Reconstruction pretrain",
    "contrast": "Contrastive pretrain",
    "reconst_noanom": "Reconstruction pretrain, no anomaly loss",
}

METHOD_ORDER = ["scratch", "reconst", "reconst_noanom", "contrast"]

COLORS = {
    "scratch": "#2F4858",
    "reconst": "#D95F02",
    "reconst_noanom": "#1B9E77",
    "contrast": "#7570B3",
}

MARKERS = {
    "scratch": "o",
    "reconst": "s",
    "reconst_noanom": "^",
    "contrast": "D",
}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Create publication-style label-efficiency figures from site main study summary.csv."
    )
    parser.add_argument(
        "--summary",
        default="runs/pohang_main_study/summary.csv",
        help="Path to summary.csv generated by summarize_pohang_main_study.py.",
    )
    parser.add_argument(
        "--out-dir",
        default=None,
        help="Output directory. Defaults to <summary parent>/figures.",
    )
    parser.add_argument(
        "--site-title",
        default="Pohang",
        help="Site name used in figure titles.",
    )
    parser.add_argument(
        "--methods",
        default=",".join(METHOD_ORDER),
        help="Comma-separated methods to plot.",
    )
    parser.add_argument(
        "--formats",
        default="png,pdf",
        help="Comma-separated output formats, e.g. png,pdf,svg.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=300,
        help="Raster output DPI.",
    )
    parser.add_argument(
        "--show-degenerate",
        action="store_true",
        help="Annotate points with specificity <= 0.05 as degenerate all-event-like predictions.",
    )
    return parser.parse_args()


def load_summary(path: Path, methods: list[str]) -> pd.DataFrame:
    df = pd.read_csv(path)
    required = {
        "method",
        "fraction",
        "test_f1",
        "test_balanced_acc",
        "test_precision",
        "test_recall",
        "test_specificity",
    }
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"Missing required columns in {path}: {missing}")

    df = df[df["method"].isin(methods)].copy()
    df["fraction"] = df["fraction"].astype(float)
    metric_cols = [
        "test_f1",
        "test_balanced_acc",
        "test_precision",
        "test_recall",
        "test_specificity",
    ]
    for col in metric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    return df.sort_values(["method", "fraction"])


def setup_matplotlib():
    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "font.size": 10,
            "axes.titlesize": 11,
            "axes.labelsize": 10,
            "legend.fontsize": 8.5,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
            "figure.titlesize": 12,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.grid": True,
            "grid.alpha": 0.22,
            "grid.linewidth": 0.7,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def plot_metric(ax, df: pd.DataFrame, methods: list[str], metric: str, ylabel: str, show_degenerate: bool):
    for method in methods:
        sub = df[df["method"] == method].sort_values("fraction")
        if sub.empty:
            continue

        label = METHOD_LABELS.get(method, method)
        ax.plot(
            sub["fraction"],
            sub[metric],
            label=label,
            color=COLORS.get(method),
            marker=MARKERS.get(method, "o"),
            linewidth=2.0,
            markersize=5.5,
        )

        if show_degenerate:
            deg = sub[sub["test_specificity"] <= 0.05]
            if not deg.empty:
                ax.scatter(
                    deg["fraction"],
                    deg[metric],
                    s=92,
                    facecolors="none",
                    edgecolors="#B22222",
                    linewidths=1.4,
                    zorder=5,
                )

    ax.set_xlabel("Labeled fraction")
    ax.set_ylabel(ylabel)
    ax.set_ylim(-0.02, 1.03)
    ax.set_xticks(sorted(df["fraction"].dropna().unique()))
    ax.set_xticklabels([format_fraction(x) for x in sorted(df["fraction"].dropna().unique())])


def format_fraction(x: float) -> str:
    if abs(x - 1.0) < 1e-9:
        return "1.0"
    return f"{x:.2f}".rstrip("0").rstrip(".")


def save_figure(fig, out_base: Path, formats: list[str], dpi: int):
    out_base.parent.mkdir(parents=True, exist_ok=True)
    for fmt in formats:
        fig.savefig(out_base.with_suffix(f".{fmt}"), dpi=dpi, bbox_inches="tight")


def make_main_figure(df: pd.DataFrame, methods: list[str], site_title: str, out_dir: Path, formats: list[str], dpi: int, show_degenerate: bool):
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.0), sharex=True)
    plot_metric(axes[0], df, methods, "test_f1", "Test F1-score", show_degenerate)
    plot_metric(axes[1], df, methods, "test_balanced_acc", "Balanced accuracy", show_degenerate)
    axes[0].set_title("(a) F1-score")
    axes[1].set_title("(b) Balanced accuracy")

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=2, frameon=False, bbox_to_anchor=(0.5, -0.08))
    fig.suptitle(f"Label Efficiency on {site_title}")
    fig.tight_layout(rect=(0, 0.08, 1, 0.94))
    save_figure(fig, out_dir / "label_efficiency_f1_balanced", formats, dpi)
    plt.close(fig)


def make_diagnostic_figure(df: pd.DataFrame, methods: list[str], site_title: str, out_dir: Path, formats: list[str], dpi: int, show_degenerate: bool):
    fig, axes = plt.subplots(1, 3, figsize=(10.2, 3.0), sharex=True)
    plot_metric(axes[0], df, methods, "test_precision", "Precision", show_degenerate)
    plot_metric(axes[1], df, methods, "test_recall", "Recall", show_degenerate)
    plot_metric(axes[2], df, methods, "test_specificity", "Specificity", show_degenerate)
    axes[0].set_title("(a) Precision")
    axes[1].set_title("(b) Recall")
    axes[2].set_title("(c) Specificity")

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=2, frameon=False, bbox_to_anchor=(0.5, -0.08))
    fig.suptitle(f"Detection Trade-offs on {site_title}")
    fig.tight_layout(rect=(0, 0.08, 1, 0.94))
    save_figure(fig, out_dir / "label_efficiency_precision_recall_specificity", formats, dpi)
    plt.close(fig)


def write_plot_table(df: pd.DataFrame, methods: list[str], out_dir: Path):
    cols = [
        "method",
        "fraction",
        "test_f1",
        "test_balanced_acc",
        "test_precision",
        "test_recall",
        "test_specificity",
        "test_tp",
        "test_tn",
        "test_fp",
        "test_fn",
    ]
    out = df[cols].copy()
    out["method_label"] = out["method"].map(lambda x: METHOD_LABELS.get(x, x))
    out["is_degenerate_specificity"] = out["test_specificity"] <= 0.05
    out = out.sort_values(
        ["fraction", "method"],
        key=lambda s: s.map({m: i for i, m in enumerate(methods)}) if s.name == "method" else s,
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    out.to_csv(out_dir / "label_efficiency_plot_table.csv", index=False)


def main():
    args = parse_args()
    setup_matplotlib()

    summary = Path(args.summary)
    out_dir = Path(args.out_dir) if args.out_dir else summary.parent / "figures"
    methods = [m.strip() for m in args.methods.split(",") if m.strip()]
    formats = [fmt.strip().lstrip(".") for fmt in args.formats.split(",") if fmt.strip()]

    df = load_summary(summary, methods)
    make_main_figure(df, methods, args.site_title, out_dir, formats, args.dpi, args.show_degenerate)
    make_diagnostic_figure(df, methods, args.site_title, out_dir, formats, args.dpi, args.show_degenerate)
    write_plot_table(df, methods, out_dir)

    print(f"[DONE] wrote figures to {out_dir}")
    for fmt in formats:
        print(f"  - {out_dir / ('label_efficiency_f1_balanced.' + fmt)}")
        print(f"  - {out_dir / ('label_efficiency_precision_recall_specificity.' + fmt)}")
    print(f"  - {out_dir / 'label_efficiency_plot_table.csv'}")


if __name__ == "__main__":
    main()
