test:
  batch_size: 16
  num_workers: 4
  pin_memory: true

  # optional
  # save_dir: "./runs/0313/test/stage1_pohang_only"
  # finetune_ckpt: "./runs/0313/finetune/stage1_pohang_only/best.pt"

data:
  test_csv: "test.csv"

  normalize: "robust"
  add_channel_dim: true
  return_meta: true